version: "3"

services:
  api:
    build:
      context: .
      target: build_image
    volumes:
      - ./:/user/src/app
      - /user/src/app/node_modules
    ports:
      - 8000:8000
    command: npm run dev